# Disable DNS
port=0

# Interface - listen on your physical interface
interface=enp88s0

# Proxy DHCP mode:
# We do NOT assign IPs. We only provide PXE options for the subnet.
# Replace 192.168.188.0 with your actual subnet if it differs.
dhcp-range=192.168.188.0,proxy

# TFTP Server
enable-tftp
tftp-root=/mnt/infra_config/tftp

# PXE Boot file
dhcp-boot=pxelinux.0

# Logging for debug
log-dhcp
log-queries
