# Disable DNS
port=0

# TFTP Server
enable-tftp
tftp-root=/tftpboot
tftp-lowercase

# DHCP Server settings
interface=enp88s0
bind-dynamic
dhcp-range=192.168.222.100,192.168.222.200,255.255.255.0,12h
dhcp-option=option:router,192.168.222.1
dhcp-option=option:dns-server,192.168.222.1

# iPXE Chainloading logic
dhcp-match=set:ipxe,175

# DEFAULT BOOT FILE
# If it is already iPXE, load the script. Otherwise, load the binary.
dhcp-boot=tag:ipxe,http://192.168.222.2:8000/api/provision/boot.ipxe
dhcp-boot=tag:!ipxe,ipxe.efi

# Logging
log-dhcp
log-queries
log-facility=-
