# Disable DNS
port=0

# TFTP Server
enable-tftp
tftp-root=/tftpboot
tftp-lowercase

# DHCP Server settings
interface=enp88s0
bind-dynamic
dhcp-range=192.168.222.100,192.168.222.200,255.255.255.0,12h
dhcp-option=option:router,192.168.222.1
dhcp-option=option:dns-server,192.168.222.1

# iPXE Chainloading logic
dhcp-match=set:efi64,option:client-arch,7
dhcp-match=set:efi64,option:client-arch,9
dhcp-match=set:ipxe,175

# Logic:
# If iPXE -> load script via HTTP
dhcp-boot=tag:ipxe,http://192.168.222.2:8000/api/provision/boot.ipxe
# If UEFI but not iPXE -> load iPXE binary
dhcp-boot=tag:efi64,ipxe.efi
# Fallback
dhcp-boot=undionly.kpxe

# Logging
log-dhcp
log-queries
log-facility=-
