"""Initial_migration

Revision ID: 39f5c478133b
Revises: 
Create Date: 2026-01-25 08:56:29.375649

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa
from sqlalchemy.dialects import postgresql

# revision identifiers, used by Alembic.
revision: str = '39f5c478133b'
down_revision: Union[str, None] = None
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('boxes',
    sa.Column('id', sa.UUID(), nullable=False),
    sa.Column('internal_sn', sa.String(), nullable=False),
    sa.Column('mac_address', postgresql.MACADDR(), nullable=False),
    sa.Column('ip_address', postgresql.INET(), nullable=True),
    sa.Column('status', sa.Enum('NEW', 'STAGING', 'INSTALLING', 'ACTIVE', 'MAINTENANCE', name='box_status'), nullable=True),
    sa.Column('location', sa.String(), nullable=True),
    sa.Column('notes', sa.Text(), nullable=True),
    sa.PrimaryKeyConstraint('id'),
    sa.UniqueConstraint('internal_sn'),
    sa.UniqueConstraint('mac_address')
    )
    op.create_table('os_images',
    sa.Column('id', sa.UUID(), nullable=False),
    sa.Column('filename', sa.String(), nullable=False),
    sa.Column('os_type', sa.Enum('DEBIAN', 'UBUNTU', name='os_type'), nullable=False),
    sa.Column('is_active', sa.Boolean(), nullable=True),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_table('system_settings',
    sa.Column('key', sa.String(), nullable=False),
    sa.Column('value', sa.String(), nullable=True),
    sa.PrimaryKeyConstraint('key')
    )
    op.create_table('components',
    sa.Column('id', sa.UUID(), nullable=False),
    sa.Column('box_id', sa.UUID(), nullable=False),
    sa.Column('type', sa.Enum('CAMERA', 'RADAR', 'GPS', 'VSM_CONTROLLER', 'ROUTER', name='component_type'), nullable=False),
    sa.Column('vendor', sa.String(), nullable=True),
    sa.Column('model', sa.String(), nullable=True),
    sa.Column('serial_number', sa.String(), nullable=True),
    sa.ForeignKeyConstraint(['box_id'], ['boxes.id'], ),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_table('port_mappings',
    sa.Column('id', sa.UUID(), nullable=False),
    sa.Column('box_id', sa.UUID(), nullable=False),
    sa.Column('logical_device', sa.Enum('RADAR', 'VSM_CONTROLLER', 'CAMERA_MAIN', name='logical_device'), nullable=False),
    sa.Column('connection_point', sa.String(), nullable=False),
    sa.ForeignKeyConstraint(['box_id'], ['boxes.id'], ),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_table('vpn_credentials',
    sa.Column('box_id', sa.UUID(), nullable=False),
    sa.Column('ca_cert', sa.Text(), nullable=False),
    sa.Column('client_cert', sa.Text(), nullable=False),
    sa.Column('client_key', sa.Text(), nullable=False),
    sa.ForeignKeyConstraint(['box_id'], ['boxes.id'], ),
    sa.PrimaryKeyConstraint('box_id')
    )
    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_table('vpn_credentials')
    op.drop_table('port_mappings')
    op.drop_table('components')
    op.drop_table('system_settings')
    op.drop_table('os_images')
    op.drop_table('boxes')
    # ### end Alembic commands ###
