"""Add SSH config to Box

Revision ID: 70d77ba1dd87
Revises: d1c0b60b75f6
Create Date: 2026-01-26 16:03:27.995026

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = '70d77ba1dd87'
down_revision: Union[str, None] = 'd1c0b60b75f6'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('boxes', sa.Column('ssh_port', sa.Integer(), nullable=True))
    op.add_column('boxes', sa.Column('ssh_username', sa.String(), nullable=True))
    op.add_column('boxes', sa.Column('ssh_password', sa.String(), nullable=True))
    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_column('boxes', 'ssh_password')
    op.drop_column('boxes', 'ssh_username')
    op.drop_column('boxes', 'ssh_port')
    # ### end Alembic commands ###
