"""add_last_seen_and_hardware_baseline

Revision ID: a3e47abc6ac9
Revises: dd33103f247b
Create Date: 2026-07-19 19:14:24.065023

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = 'a3e47abc6ac9'
down_revision: Union[str, None] = 'dd33103f247b'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('boxes', sa.Column('hardware_baseline', sa.JSON(), nullable=True))
    op.add_column('boxes', sa.Column('last_seen', sa.DateTime(), nullable=True))
    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_column('boxes', 'last_seen')
    op.drop_column('boxes', 'hardware_baseline')
    # ### end Alembic commands ###
