"""Add type to ComponentDefinition

Revision ID: b25a84df24e6
Revises: 70d77ba1dd87
Create Date: 2026-01-26 16:26:25.000874

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = 'b25a84df24e6'
down_revision: Union[str, None] = '70d77ba1dd87'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('component_definitions', sa.Column('type', sa.String(), nullable=True))
    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_column('component_definitions', 'type')
    # ### end Alembic commands ###
