"""Add status to OsImage

Revision ID: cea35adbf04f
Revises: be6f420ef3d9
Create Date: 2026-05-04 11:30:10.968509

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = 'cea35adbf04f'
down_revision: Union[str, None] = 'be6f420ef3d9'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('os_images', sa.Column('status', sa.String(), nullable=True))
    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_column('os_images', 'status')
    # ### end Alembic commands ###
