"""Add Device Groups

Revision ID: d1c0b60b75f6
Revises: c01b5ed9702c
Create Date: 2026-01-26 14:56:46.941240

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = 'd1c0b60b75f6'
down_revision: Union[str, None] = 'c01b5ed9702c'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('device_groups',
    sa.Column('id', sa.UUID(), nullable=False),
    sa.Column('name', sa.String(), nullable=False),
    sa.Column('description', sa.String(), nullable=True),
    sa.PrimaryKeyConstraint('id'),
    sa.UniqueConstraint('name')
    )
    op.create_table('box_device_groups',
    sa.Column('box_id', sa.UUID(), nullable=False),
    sa.Column('group_id', sa.UUID(), nullable=False),
    sa.ForeignKeyConstraint(['box_id'], ['boxes.id'], ),
    sa.ForeignKeyConstraint(['group_id'], ['device_groups.id'], ),
    sa.PrimaryKeyConstraint('box_id', 'group_id')
    )
    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_table('box_device_groups')
    op.drop_table('device_groups')
    # ### end Alembic commands ###
