"""add_location_provision_fields_and_hardware_inventory

Revision ID: dd33103f247b
Revises: 7c4f526d09bc
Create Date: 2026-07-19 11:55:53.547408

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = 'dd33103f247b'
down_revision: Union[str, None] = '7c4f526d09bc'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('boxes', sa.Column('hardware_inventory', sa.JSON(), nullable=True))
    op.add_column('locations', sa.Column('timezone', sa.String(), nullable=False, server_default='UTC'))
    op.add_column('locations', sa.Column('locale', sa.String(), nullable=False, server_default='en_US.UTF-8'))
    op.add_column('locations', sa.Column('keyboard', sa.String(), nullable=False, server_default='us'))
    op.add_column('locations', sa.Column('gateway', sa.String(), nullable=True))
    op.add_column('locations', sa.Column('netmask', sa.String(), nullable=True))
    op.add_column('locations', sa.Column('dns_server', sa.String(), nullable=True))
    op.add_column('locations', sa.Column('ntp_server', sa.String(), nullable=True))
    op.add_column('locations', sa.Column('package_mirror', sa.String(), nullable=True))
    op.add_column('locations', sa.Column('ssh_public_key', sa.Text(), nullable=True))
    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_column('locations', 'ssh_public_key')
    op.drop_column('locations', 'package_mirror')
    op.drop_column('locations', 'ntp_server')
    op.drop_column('locations', 'dns_server')
    op.drop_column('locations', 'netmask')
    op.drop_column('locations', 'gateway')
    op.drop_column('locations', 'keyboard')
    op.drop_column('locations', 'locale')
    op.drop_column('locations', 'timezone')
    op.drop_column('boxes', 'hardware_inventory')
    # ### end Alembic commands ###
