"""add_locations_and_migrate_data

Revision ID: e421fded4ad2
Revises: b25a84df24e6
Create Date: 2026-01-30 15:24:53.762810

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = 'e421fded4ad2'
down_revision: Union[str, None] = 'b25a84df24e6'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('locations',
    sa.Column('id', sa.UUID(), nullable=False),
    sa.Column('name', sa.String(), nullable=False),
    sa.Column('description', sa.Text(), nullable=True),
    sa.PrimaryKeyConstraint('id'),
    sa.UniqueConstraint('name')
    )
    op.add_column('boxes', sa.Column('location_id', sa.UUID(), nullable=True))
    op.create_foreign_key(None, 'boxes', 'locations', ['location_id'], ['id'])
    
    # --- Custom Data Migration ---
    import uuid
    bind = op.get_bind()
    # Select distinct legacy locations
    # Use text() for raw SQL
    results = bind.execute(sa.text("SELECT DISTINCT location FROM boxes WHERE location IS NOT NULL")).fetchall()
    
    for r in results:
        loc_name = r[0]
        if not loc_name: continue
        
        loc_id = str(uuid.uuid4())
        
        # Insert into locations table
        bind.execute(
            sa.text("INSERT INTO locations (id, name) VALUES (:id, :name)"),
            {"id": loc_id, "name": loc_name}
        )
        
        # Update boxes to reference new location_id
        bind.execute(
            sa.text("UPDATE boxes SET location_id = :loc_id WHERE location = :loc_name"),
            {"loc_id": loc_id, "loc_name": loc_name}
        )
    # -----------------------------

    op.drop_column('boxes', 'location')
    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('boxes', sa.Column('location', sa.VARCHAR(), autoincrement=False, nullable=True))
    op.drop_constraint(None, 'boxes', type_='foreignkey')
    op.drop_column('boxes', 'location_id')
    op.drop_table('locations')
    # ### end Alembic commands ###
