"""Refactor Component model to use definition_id

Revision ID: f0d33e698bc4
Revises: 6b1a782d421e
Create Date: 2026-01-26 09:22:27.628158

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa
from sqlalchemy.dialects import postgresql

# revision identifiers, used by Alembic.
revision: str = 'f0d33e698bc4'
down_revision: Union[str, None] = '6b1a782d421e'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('components', sa.Column('definition_id', sa.UUID(), nullable=False))
    op.create_foreign_key(None, 'components', 'component_definitions', ['definition_id'], ['id'])
    op.drop_column('components', 'type')
    op.drop_column('components', 'model')
    op.drop_column('components', 'vendor')
    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('components', sa.Column('vendor', sa.VARCHAR(), autoincrement=False, nullable=True))
    op.add_column('components', sa.Column('model', sa.VARCHAR(), autoincrement=False, nullable=True))
    op.add_column('components', sa.Column('type', postgresql.ENUM('CAMERA', 'RADAR', 'GPS', 'VSM_CONTROLLER', 'ROUTER', name='component_type'), autoincrement=False, nullable=False))
    op.drop_constraint(None, 'components', type_='foreignkey')
    op.drop_column('components', 'definition_id')
    # ### end Alembic commands ###
